site_name: bmyjacks Knowledge Base
site_url: https://kb.bmyjacks.io/
site_description: Learn knowledge interestingly.
site_author: bmyjacks
repo_url: https://github.com/bmyjacks/kb.bmyjacks.io
repo_name: bmyjacks/kb.bmyjacks.io
edit_uri: edit/dev/docs/

theme:
  name: material
  custom_dir: overrides
  font: false
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.prune
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - search.suggest
    - search.share
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - stylesheets/fonts.css

plugins:
  - search
  - git-committers:
      enabled: !ENV [CI, false]
      repository: bmyjacks/kb.bmyjacks.io
      branch: main
  - minify:
      minify_html: true
      minify_js: false
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - stylesheets/fonts.css

copyright: Copyright &copy; 2024 bmyjacks. <p xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"></a></p> <p><a href="#__consent">Change cookie settings</a></p>

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra:
  analytics:
    provider: google
    property: G-HJPMY5RN0R
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage

nav:
  - Home:
      - "Welcome": "index.md"
      - "About me": "about.md"
      - "Cookie policy": "cookie.md"
  - Markdown:
      - "Get started": "markdown/index.md"
      - "Basic usage": "markdown/basic.md"
